# Generated by Django 3.2.8 on 2021-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acucares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'acucares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'nacionalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'uvas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UvasVinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_uva', models.IntegerField()),
            ],
            options={
                'db_table': 'uvas_vinhos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('safra', models.IntegerField()),
                ('vinicola', models.CharField(max_length=45)),
                ('alcool', models.DecimalField(decimal_places=1, max_digits=2)),
                ('temperatura', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('guarda', models.IntegerField()),
                ('amadurecimento', models.CharField(max_length=256)),
                ('visual', models.CharField(max_length=45)),
                ('olfativo', models.CharField(max_length=512)),
                ('gustativo', models.CharField(max_length=512)),
                ('destaque', models.IntegerField()),
                ('promocao', models.IntegerField()),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('numero_avaliacoes', models.IntegerField()),
                ('maior_avaliacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('ativo', models.IntegerField()),
                ('data_criacao', models.DateField()),
                ('data_atualizacao', models.DateField()),
            ],
            options={
                'db_table': 'vinhos',
                'managed': False,
            },
        ),
    ]
